name: eg
gateway:
  provider:
    type: Kubernetes
  service:
    type: NodePort
    ports:
      - name: https
        port: 443
        protocol: TCP
        nodePort: 32443
        targetPort: 443
controller:
  resources:
    requests: { cpu: "100m", memory: "128Mi" }
    limits: { cpu: "500m", memory: "512Mi" }
