apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgbot
  namespace: tgbot
  labels:
    app: tgbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgbot
  template:
    metadata:
      labels:
        app: tgbot
    spec:
      containers:
        - name: tgbot
          image: ghcr.io/cyprus7/ranger-odyssey/tgbot:d864460d3ce26a75474309667a0123f622f21b47
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: tgbot-config
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
