image:
  repository: ghcr.io/cyprus7/ranger-odyssey
  tag: 145f38b94d09dc6531de8c0ef1d3ecac1be0a51a
host: quests.tmbot.cc
tlsSecretName: quests-tmbot-cc-tls
apiPath: /api
letsencrypt:
  email: letsencrypt@mail.ru
ingress:
  enabled: false
app:
  replicas: 4
  canary: false
frontend:
  replicas: 2
  resources: {}
backend:
  replicas: 2
  resources: {}
externalSecrets:
  enabled: true
  storeName: vault-kv
  path: app/prod
