image:
  repository: ghcr.io/cyprus7/ranger-odyssey
  tag: e68255f58ed14e5e3c9f5e9ea9ec96fdf2a59d5e
host: quests.tmbot.cc
tlsSecretName: quests-tmbot-cc-tls
apiPath: /api
letsencrypt:
  email: letsencrypt@mail.ru
ingress:
  enabled: false
app:
  replicas: 4
  canary: false
frontend:
  replicas: 2
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 500m
backend:
  replicas: 2
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 500m
externalSecrets:
  enabled: true
  storeName: vault-kv
  path: app/prod
tgbot:
  enabled: true
  replicas: 2
  port: 3000
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 500m
