apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ranger-tmbot-cc
  namespace: prod
spec:
  secretName: tls-quests-tmbot-cc
  dnsNames: [ "quests.tmbot.cc" ]
  issuerRef:
    name: letsencrypt-gw
    kind: Issuer
