apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: stub-tg-link-route
  namespace: sandbox
spec:
  parentRefs:
    - name: eg           # change to your Gateway resource name
      namespace: envoy-gateway
  hostnames:
    - {{ .Values.host | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /tg-link-generate
      backendRefs:
        - backendRef:
            name: stub-tg-link
            port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /api/generate
      backendRefs:
        - backendRef:
            name: stub-tg-link
            port: 80
