apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: stub-tg-link-route
  namespace: prod
spec:
  hostnames:
    - "quests.tmbot.cc"
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: web
      sectionName: https
      namespace: prod
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /tg-link-generate
      backendRefs:
        - name: stub-tg-link
          namespace: stub
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /api/generate
      backendRefs:
        - name: stub-tg-link
          namespace: stub
          port: 80
