apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-lite-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 30s

    # Скрейп по аннотациям сервисов (namespace=prod)
    scrape_configs:
      - job_name: kubernetes-annotated
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: ["prod"]

        relabel_configs:
          # 1) Только сервисы с prometheus.io/scrape="true"
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: "true"

          # 2) Путь метрик из аннотации (если задан)
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: "(.+)"
            replacement: ${1}

          # 3) Адрес таргета: <pod_ip>:<port из аннотации>
          - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: "(.+);(.+)"
            replacement: ${1}:${2}

          # 4) Удобные лейблы
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: service
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node

          # 5) Делаем job равным имени сервиса (api, tgbot, …)
          - source_labels: [__meta_kubernetes_service_name]
            target_label: job

      # (опционально) сам prom-lite
      - job_name: prom-lite
        static_configs:
          - targets: ['localhost:9090']
