apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: sandbox
spec:
  refreshInterval: 1m
  secretStoreRef: { name: vault-kv, kind: ClusterSecretStore }
  target: { name: app-secrets }
  data:
    - secretKey: POSTGRES_URL
      remoteRef: { key: app/sandbox, property: POSTGRES_URL }
    - secretKey: REDIS_URL
      remoteRef: { key: app/sandbox, property: REDIS_URL }
    - secretKey: BOT_TOKEN
      remoteRef: { key: app/sandbox, property: BOT_TOKEN }
    - secretKey: JWT_SECRET
      remoteRef: { key: app/sandbox, property: JWT_SECRET }
