apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: quests-gateway
  namespace: sandbox
spec:
  selector:
    istio: ingressgateway # use Istio default gateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        privateKey: /etc/istio/ingressgateway/certs/server.key
        serverCertificate: /etc/istio/ingressgateway/certs/server.crt
  allowedRoutes:
    namespaces:
      from: All
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: quests
  namespace: sandbox
spec:
  hosts:
    - "quests.tmbot.cc"
  gateways:
    - quests-gateway
  http:
    - match:
        - uri:
            prefix: /api
      rewrite:
        uri: /
      route:
        - destination:
            host: quests-service
            port:
              number: 80
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: quests-service
            port:
              number: 80
