apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: web-proxy
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        patch:
          type: StrategicMerge
          value:
            spec:
              type: NodePort
              ports:
                - name: http
                  port: 80
                  protocol: TCP
                  targetPort: 80
                  nodePort: 32080
                - name: https
                  port: 443
                  protocol: TCP
                  targetPort: 443
                  nodePort: 32443
