apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-quests
spec:
  hostnames:
    - {{ .Values.host | quote }}
  parentRefs:
    # HTTP listener (для ACME и редиректа)
    - name: web
      sectionName: http
    # HTTPS listener (основной трафик)
    - name: web
      sectionName: https
  rules:
    # 1. ACME HTTP-01 challenge — пропускаем без редиректа
    - matches:
        - path:
            type: PathPrefix
            value: /.well-known/acme-challenge/
      backendRefs:
        - name: {{ printf "cm-acme-http-solver-%%s" .Release.Namespace }}
          port: 8089

    # 2. HTTP -> HTTPS редирект (всё, что не challenge)
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301

    # 3. /api через HTTPS -> API сервис (HTTP:80 внутри кластера)
    - matches:
        - path:
            type: PathPrefix
            value: {{ default "/api" .Values.apiPath | quote }}
      backendRefs:
        - name: api
          port: 80

    # 4. Остальное через HTTPS -> frontend сервис (HTTP:80 внутри кластера)
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend
          port: 80
