apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-quests
spec:
  hostnames:
    - {{ .Values.host | quote }}
  parentRefs:
    - name: web
      sectionName: https
  rules:
    # Telegram webhook -> tgbot
    - matches:
        - path:
            type: PathPrefix
            value: /tgbot/webhook
          method: POST
      backendRefs:
        - name: tgbot
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: {{ default "/api" .Values.apiPath | quote }}
      backendRefs:
        - name: api
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /metrics
      backendRefs:
        - name: api
          port: 9464
        - name: tgbot
          port: 9464
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend
          port: 80
