apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend
spec:
  hostnames: [ {{ .Values.host | quote }} ]
  parentRefs: [ { name: web } ]
  rules:
    - matches: [ { path: { type: PathPrefix, value: "/" } } ]
      backendRefs: [ { name: frontend, port: 80 } ]

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api
spec:
  hostnames: [ {{ .Values.host | quote }} ]
  parentRefs: [ { name: web } ]
  rules:
    - matches: [ { path: { type: PathPrefix, value: "/api" } } ]
      backendRefs: [ { name: api, port: 80 } ]
