apiVersion: v1
kind: Service
metadata:
  name: cm-acme-http-solver
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cm-acme-http-solver
spec:
  type: ClusterIP
  selector:
    # Эти лейблы выставляет cert-manager на поде solver'а
    acme.cert-manager.io/http01-solver: "true"
    acme.cert-manager.io/http-domain: {{ .Values.host | quote }}
  ports:
    - name: http01
      port: 8089
      targetPort: 8089
      protocol: TCP
