apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stub-tg-link
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/your-repo' # <-- replace with your repository URL
    targetRevision: HEAD
    path: infra/apps/stub_tg_link
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sandbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
