apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stub-tg-link
  namespace: argocd
spec:
  project: stub-tg-link
  source:
    repoURL: 'https://github.com/cyprus7/ranger-odyssey.git'
    targetRevision: HEAD
    path: infra/apps/stub_tg_link
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: stub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
