name: CD
on:
  push:
    branches: [develop, main]
permissions:
  contents: write
  packages: write
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend:${{ github.sha }} ./backend
          docker build -t ghcr.io/${{ github.repository }}/frontend:${{ github.sha }} ./frontend
          docker push ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}

      - name: Bump image tag in Helm values (env)
        run: |
          ENV_DIR=$([ "${{ github.ref_name }}" = "main" ] && echo infra/envs/prod || echo infra/envs/sandbox)
          pip install yq >/dev/null 2>&1 || true
          yq -iy '.image.tag = "${{ github.sha }}"' "$ENV_DIR/values.yaml"

      - name: Commit & push
        run: |
          git config user.name "ranger-quests-bot"
          git config user.email "bot@users.noreply.github.com"
          git add -A
          git commit -m "deploy: ${{ github.sha }}" || echo "no changes"
          git push
